---
title: "Advent Cdoe"
author: "Dusty Turner"
date: "12/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

```{r, include=FALSE}
library(tidyverse)
```

## Thirteenth Day of Advent

```{r}
input_13 <-
  tibble(x = read_lines(here::here("data_files", "advent13data.txt"))) 

# busses <-
input_13 %>% 
  tail(1) %>% 
  mutate(x = str_remove_all(x, ",x")) %>% 
  separate_rows(x,sep = ",", convert = T) %>% 
  rowwise() %>% 
  mutate(bus_times = str_c(seq(from = 0, to = as.numeric(input_13$x[1])*2, by = x), collapse = ",")) %>% 
  separate_rows(bus_times, sep = ",", convert = T) %>% 
  group_by(x) %>% 
  filter(bus_times > as.numeric(input_13$x[1])) %>% 
  arrange(bus_times) %>% 
  mutate(wait_time = bus_times - as.numeric(input_13$x[1])) %>% 
  mutate(answer = x * wait_time)


```

## Twelth Day of Advent

```{r}
input_12 <-
  tibble(x = read_lines(here::here("data_files", "advent12data.txt")))
  # tibble(x = read_lines(here::here("data_files", "advent12data_test.txt")))


next_step <-
input_12 %>% 
  mutate(direction = str_sub(x,1,1), movement = as.numeric(str_sub(x,2,nchar(x)))) 



stepper <- function(action, current_location){
bind_cols(action, current_location) %>% 
  mutate(east = case_when(direction == "F" & facing == "east" ~ east + movement,
                           direction == "F" & facing == "west" ~ east - movement,
                          TRUE ~ east)) %>% 
  mutate(north = case_when(direction == "F" & facing == "north" ~ north + movement,
                           direction == "F" & facing == "south" ~ north - movement,
                           TRUE ~ north)) %>% 
  mutate(facing = case_when(direction == "L" & facing == "east" & movement == 90 ~ "north",
                            direction == "L" & facing == "north" & movement == 90 ~ "west",
                            direction == "L" & facing == "west" & movement == 90 ~ "south",
                            direction == "L" & facing == "south" & movement == 90 ~ "east",
                            TRUE ~ facing)) %>% 
  mutate(facing = case_when(direction == "L" & facing == "east" & movement == 180 ~ "west",
                            direction == "L" & facing == "north" & movement == 180 ~ "south",
                            direction == "L" & facing == "west" & movement == 180 ~ "east",
                            direction == "L" & facing == "south" & movement == 180 ~ "north",
                            TRUE ~ facing)) %>% 
  mutate(facing = case_when(direction == "L" & facing == "east" & movement == 270 ~ "south",
                            direction == "L" & facing == "north" & movement == 270 ~ "east",
                            direction == "L" & facing == "west" & movement == 270 ~ "north",
                            direction == "L" & facing == "south" & movement == 270 ~ "west",
                            TRUE ~ facing)) %>% 
  mutate(facing = case_when(direction == "R" & facing == "east" & movement == 90 ~ "south",
                            direction == "R" & facing == "south" & movement == 90 ~ "west",
                            direction == "R" & facing == "west" & movement == 90 ~ "north",
                            direction == "R" & facing == "north" & movement == 90 ~ "east",
                            TRUE ~ facing)) %>% 
  mutate(facing = case_when(direction == "R" & facing == "east" & movement == 180 ~ "west",
                            direction == "R" & facing == "south" & movement == 180 ~ "north",
                            direction == "R" & facing == "west" & movement == 180 ~ "east",
                            direction == "R" & facing == "north" & movement == 180 ~ "south",
                            TRUE ~ facing)) %>% 
  mutate(facing = case_when(direction == "R" & facing == "east" & movement == 270 ~ "north",
                            direction == "R" & facing == "south" & movement == 270 ~ "east",
                            direction == "R" & facing == "west" & movement == 270 ~ "south",
                            direction == "R" & facing == "north" & movement == 270 ~ "west",
                            TRUE ~ facing)) %>% 
  mutate(north = case_when(direction == "N" ~ north + movement,
                          direction == "S"~ north - movement,
                          TRUE ~ north)) %>% 
  mutate(east = case_when(direction == "E" ~ east + movement,
                          direction == "W"~ east - movement,
                          TRUE ~ east))
}
  

current_location <- tibble(east = 0, north = 0, facing = "east")

i <- 1


for (i in 1:nrow(next_step)) {
# for (i in 1:20) {
# print(i)  

# print(next_step[i,])
  
last_input <-
  current_location %>% tail(1) %>% 
stepper(action = next_step[i,]) %>% 
  select(east,north,facing)

current_location <- 
  current_location %>% bind_rows(last_input)

# print(current_location)
}

## answer
current_location %>% 
  tail(1) %>% 
  mutate(man_dist = abs(east)+abs(north))


## drob's stuff

instructions <-
input_12 %>% 
    mutate(instruction = str_sub(x,1,1), amount = as.numeric(str_sub(x,2,nchar(x)))) 

direction <- c("E", "S", "W", "N")

changes <-
tribble(~ direction, ~ x_change, ~ y_change,
"E",1,0,
"S",0,-1,
"W",-1,0,
"N",0,1)

drob <-
instructions %>% 
  select(-x) %>% 
  mutate(angle_change = case_when(instruction == "L" ~ -amount/90,
                                  instruction == "R" ~ amount/90,
                                  TRUE ~ 0),
         facing = directions[1 + cumsum(angle_change) %% 4],
         direction = ifelse(instruction == "F", facing, instruction)) %>% 
  left_join(changes, by = "direction") %>% 
  replace_na(list(x_change = 0, y_change = 0)) %>% 
  mutate(x = cumsum(x_change * amount),
         y = cumsum(y_change * amount)) %>% 
  mutate(iteration = row_number()) 
  # slice(1:20)

bind_cols(
  bind_rows(tibble(x=0,y=0), drob),
  current_location,
) %>% 
  relocate(x,y,east,north) %>% tail() %>% 
  mutate(man_dist = abs(east)+abs(north))
  # filter(row_number() %in% 10:20)

```


```{r}
input_12

next_step <-
input_12 %>% 
  mutate(direction = str_sub(x,1,1), movement = as.numeric(str_sub(x,2,nchar(x)))) 

current_location <- tibble(east = 0, north = 0, facing = "east", way_east = 10, way_north = 1)

action <- next_step[1,]

stepper(action = action,current_location = current_location)

stepper <- function(action, current_location){
bind_cols(action, current_location) %>%
  mutate(prev_way_east = way_east, prev_way_north = way_north) %>% 
  mutate(prev_east = east, prev_north = north) %>% 
  mutate(east = case_when(direction == "F" ~ prev_east + movement*prev_way_east,
                          TRUE ~ east)) %>% 
  mutate(north = case_when(direction == "F" ~ prev_north + movement*prev_way_north,
                          TRUE ~ north)) %>% 
  mutate(way_north = case_when(direction == "N" ~ prev_way_north + movement,
                               direction == "S" ~ prev_way_north - movement,
                               TRUE ~ way_north)) %>% 
  mutate(way_east = case_when(direction == "E" ~ prev_way_east + movement,
                               direction == "W" ~ prev_way_east - movement,
                               TRUE ~ way_east)) %>% 
  mutate(way_north = case_when(direction == "L" & movement == 90 ~ prev_way_east,
                               direction == "L" & movement == 180 ~ -1 * prev_way_north,
                               direction == "L" & movement == 270 ~ -1 * prev_way_east,
                               TRUE ~ way_north
                               )) %>% 
  mutate(way_north = case_when(direction == "R" & movement == 90 ~ -1 * prev_way_east,
                               direction == "R" & movement == 180 ~ -1 * prev_way_north,
                               direction == "R" & movement == 270 ~ prev_way_east,
                               TRUE ~ way_north
                               )) %>% 
  mutate(way_east = case_when(direction == "L" & movement == 90 ~ -1 * prev_way_north,
                               direction == "L" & movement == 180 ~ -1 * prev_way_east,
                               direction == "L" & movement == 270 ~ prev_way_north,
                               TRUE ~ way_east
                               )) %>% 
  mutate(way_east = case_when(direction == "R" & movement == 90 ~ prev_way_north,
                               direction == "R" & movement == 180 ~ -1 * prev_way_east,
                               direction == "R" & movement == 270 ~ -1 * prev_way_north,
                               TRUE ~ way_east
                               )) 

  
}
  
current_location <- tibble(east = 0, north = 0, facing = "east", way_east = 10, way_north = 1)

i <- 1


for (i in 1:nrow(next_step)) {
# for (i in 1:20) {
# print(i)  

# print(next_step[i,])
  
last_input <-
  current_location %>% tail(1) %>% 
stepper(action = next_step[i,]) %>% 
  select(east,north,facing, way_east, way_north)

current_location <- 
  current_location %>% bind_rows(last_input)

# print(current_location)
}

## answer
current_location %>% 
  tail(1) %>% 
  mutate(man_dist = abs(east)+abs(north))


```


## Eleventh Day of Advent

```{r}
library(tidytext)
input_11 <-
  # tibble(x = read_lines(here::here("data_files", "advent11data.txt")))
  tibble(x = read_lines(here::here("data_files", "advent11data.txt")))

data <-
input_11 %>%
  mutate(row = row_number()) %>% 
  relocate(row) %>%
  mutate(x = str_replace_all(string = x, pattern = "\\.", "x")) %>% 
  unnest_characters(character, x) %>% 
  group_by(row) %>% 
  mutate(col = row_number()) %>% 
  ungroup() %>% 
  pivot_wider(names_from = col, values_from = character) %>% 
  janitor::clean_names() %>% 
  select(-row)

counter <- function(row, col, input = data){
input %>% 
  filter(row_number() %in% c((row-1):(row+1))) %>% 
  select(any_of(c((col-1):(col+1)))) %>% 
  pivot_longer(cols = everything()) %>% 
  count(value)
}

# data[row_of_interest,col_of_interest]

# counter(row = row_of_interest, col = col_of_interest)

assign_seat <- function(row = row_of_interest, col = col_of_interest, input = data) {
  if (unlist(input[row, col]) == "l") {
    temp <-
      counter(row = row, col = col, input = input) %>%
      filter(value == "#") %>% pull(n) %>% is_empty()
    new_seat_type <- if_else(temp,"#", "l")
  } else if (unlist(input[row, col]) == "#") {
    new_seat_type <-
      counter(row = row, col = col, input = input) %>%
      filter(value == "#") %>%
      mutate(n = n-1) %>% 
      summarise(seat = if_else(n >= 4, "l", "#")) %>%
      pull(seat)
  } else{
    new_seat_type <- "x"
  }
  return(new_seat_type)
  
  # new_data[row,col] <- new_seat_type
  
  return(new_data)
}

# row_of_interest <- 3
# col_of_interest <- 1
# 
# data
# 
# assign_seat(row = row_of_interest, col = col_of_interest, input = data)

# list_x <- rep(1:nrow(data),ncol(data)) %>% sort()
# list_y <- rep(1:nrow(data),ncol(data))
list_x <- rep(1:nrow(data),ncol(data)) %>% sort()
list_y <- rep(1:ncol(data),nrow(data))

# x <- list_x
# y <- list_y

library(furrr)
plan(multiprocess)

iterate <- function(input, x, y){
  output <-
future_map2_chr(.x = x,.y = y, .f = ~assign_seat(row = .x,col = .y,input = input),.progress = T) %>% 
  matrix(nrow = nrow(input), byrow = T) %>% as.data.frame() %>% magrittr::set_colnames(colnames(input))

  occupied <-
  tibble(output) %>% 
    pivot_longer(cols = everything()) %>% 
    count(value) %>% filter(value == "#") %>% 
    pull(n)

  # print(output)  
message(str_c("data frames are identical: ", identical(input,output), " with occupied = ", occupied))
  return(output)  
  
}


# iterate(input = data,x = x, y = y)

data %>% 
iterate(x = list_x, y = list_y) %>% #1
iterate(x = list_x, y = list_y) %>% #2
iterate(x = list_x, y = list_y) %>% #3
iterate(x = list_x, y = list_y) %>%  
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y)     #9

.Last.value %>% 
iterate(x = list_x, y = list_y) %>% #10
iterate(x = list_x, y = list_y) %>% #11
iterate(x = list_x, y = list_y) %>% #12
iterate(x = list_x, y = list_y) %>%  
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y)     #9

.Last.value %>% 
iterate(x = list_x, y = list_y) %>% #10
iterate(x = list_x, y = list_y) %>% #11
iterate(x = list_x, y = list_y) %>% #12
iterate(x = list_x, y = list_y) %>%  
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% #10
iterate(x = list_x, y = list_y) %>% #11
iterate(x = list_x, y = list_y) %>% #12
iterate(x = list_x, y = list_y) %>%  
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% #10
iterate(x = list_x, y = list_y) %>% #11
iterate(x = list_x, y = list_y) %>% #12
iterate(x = list_x, y = list_y) %>%  
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% #10
iterate(x = list_x, y = list_y) %>% #11
iterate(x = list_x, y = list_y) %>% #12
iterate(x = list_x, y = list_y) %>%  
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% #10
iterate(x = list_x, y = list_y) %>% #11
iterate(x = list_x, y = list_y) %>% #12
iterate(x = list_x, y = list_y) %>%  
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% #10
iterate(x = list_x, y = list_y) %>% #11
iterate(x = list_x, y = list_y) %>% #12
iterate(x = list_x, y = list_y) %>%  
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% #10
iterate(x = list_x, y = list_y) %>% #11
iterate(x = list_x, y = list_y) %>% #12
iterate(x = list_x, y = list_y) %>%  
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% #10
iterate(x = list_x, y = list_y) %>% #11
iterate(x = list_x, y = list_y) %>% #12
iterate(x = list_x, y = list_y) %>%  
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% #10
iterate(x = list_x, y = list_y) %>% #11
iterate(x = list_x, y = list_y) %>% #12
iterate(x = list_x, y = list_y) %>%  
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% #10
iterate(x = list_x, y = list_y) %>% #11
iterate(x = list_x, y = list_y) %>% #12
iterate(x = list_x, y = list_y) %>%  
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% #10
iterate(x = list_x, y = list_y) %>% #11
iterate(x = list_x, y = list_y) %>% #12
iterate(x = list_x, y = list_y) %>%  
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y) %>% 
iterate(x = list_x, y = list_y)     #9

result <- .Last.value

```

## Eleven B

```{r}

# data <- data_backup 

# row <- 7
# col <- 5


# counter_b(row = 1,col = 1, input = data)

counter_b <- function(row, col, input = data) {
  # check right
  i = 1
  check = "x"
  occupied_counter <- 0
  empty_counter <- 0
  while (check == "x" & (col + i) <= ncol(input)) {
    check =
      input %>%
      filter(row_number() %in% row) %>%
      select(any_of(col + i)) %>%
      pull()
    
    i = i + 1
    occupied_counter = occupied_counter + (check == "#")
    empty_counter = empty_counter + (check == "l")
    # print(i)
  }
  
  # checks left
  i = 1
  check = "x"
  while (check == "x" & (col - i) >= 1) {
    check =
      input %>%
      filter(row_number() %in% row) %>%
      select(any_of(col - i)) %>%
      pull()
    
    i = i + 1
    occupied_counter = occupied_counter + (check == "#")
    empty_counter = empty_counter + (check == "l")
    # print(i)
  }
  
  # checks down
  i = 1
  check = "x"
  while (check == "x" & (row + i) <= nrow(input)) {
    check =
      input %>%
      select(any_of(col)) %>%
      filter(row_number() %in% (row + i)) %>%
      pull()
    
    i = i + 1
    occupied_counter = occupied_counter + (check == "#")
    empty_counter = empty_counter + (check == "l")
    # print(i)
  }
  
  # checks up
  i = 1
  check = "x"
  while (check == "x" & (row - i) >= 1) {
    check =
      input %>%
      select(any_of(col)) %>%
      filter(row_number() %in% (row - i)) %>%
      pull()
    
    i = i + 1
    occupied_counter = occupied_counter + (check == "#")
    empty_counter = empty_counter + (check == "l")
    # print(i)
  }
  
  # checks down right
  i = 1
  check = "x"
  while (check == "x" &
         (row + i) <= nrow(input) & (col + i) <= ncol(input)) {
    check =
      input %>%
      select(any_of(col + i)) %>%
      filter(row_number() %in% (row + i)) %>%
      pull()
    
    i = i + 1
    occupied_counter = occupied_counter + (check == "#")
    empty_counter = empty_counter + (check == "l")
    # print(i)
  }
  
  # checks up right
  i = 1
  check = "x"
  while (check == "x" & (row - i) >= 1 & (col + i) <= ncol(input)) {
    check =
      input %>%
      select(any_of(col + i)) %>%
      filter(row_number() %in% (row - i)) %>%
      pull()
    
    i = i + 1
    occupied_counter = occupied_counter + (check == "#")
    empty_counter = empty_counter + (check == "l")
    # print(i)
  }
  
  # checks down left
  i = 1
  check = "x"
  while (check == "x" & (row + i) <= nrow(input) & (col - i) >= 1) {
    check =
      input %>%
      select(any_of(col - i)) %>%
      filter(row_number() %in% (row + i)) %>%
      pull()
    
    i = i + 1
    occupied_counter = occupied_counter + (check == "#")
    empty_counter = empty_counter + (check == "l")
    # print(i)
  }
  
  # checks up left
  i = 1
  check = "x"
  while (check == "x" & (row - i) >= 1 & (col - i) >= 1) {
    check =
      input %>%
      select(any_of(col - i)) %>%
      filter(row_number() %in% (row - i)) %>%
      pull()
    
    i = i + 1
    occupied_counter = occupied_counter + (check == "#")
    empty_counter = empty_counter + (check == "l")
    # print(i)
  }

  
    
return(list(occupied_counter = occupied_counter, empty_counter = empty_counter))
  
}

assign_seat_b <- function(row, col, input = data) {
  
  seat_type =
    input %>%
    filter(row_number() == row) %>%
    select(any_of(col)) %>%
    pull()
  
  if(seat_type == "x")  {
    new_seat = "x"
  } else if(seat_type == "#"){
    counted <- counter_b(row = row, col = col, input = input)$occupied_counter
    if(counted >=5){new_seat = "l"} else{new_seat = "#"}
  } else if(seat_type == "l"){
    counted <- counter_b(row = row, col = col, input = input)$occupied_counter
    if(counted == 0){new_seat = "#"} else{new_seat = "l"}
  }
  
  return(new_seat)
    
}

# assign_seat_b(row = 1,col = 2,input = data)

library(furrr)
plan(multiprocess)

row_list <- rep(1:nrow(data),ncol(data)) %>% sort()
col_list <- rep(1:ncol(data),nrow(data))


iterate_b <- function(input, x, y){
  output <-
future_map2_chr(.x = x,.y = y, .f = ~assign_seat_b(row = .x,col = .y,input = input),.progress = T) %>% 
  matrix(nrow = nrow(input), byrow = T) %>% as.data.frame() %>% magrittr::set_colnames(colnames(input))

  occupied <-
  tibble(output) %>%
    pivot_longer(cols = everything()) %>%
    count(value) %>% filter(value == "#") %>%
    pull(n)

  # print(output)
message(str_c("data frames are identical: ", identical(input,output), " with occupied = ", occupied))
  return(output)

}

data %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) 

.Last.value %>% 
  iterate_b(x = row_list, y = col_list)

.Last.value %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>%
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list) %>% 
  iterate_b(x = row_list, y = col_list)
  

```




## Tenth Day of Advent

```{r}
library(tidyverse)
library(compositions)

input_10 <-
  tibble(x = read_lines(here::here("data_files", "advent10data.txt"))) %>% 
  mutate(x = as.numeric(x)) %>% 
  arrange(x) 

input_10 %>% 
  mutate(lag = lag(x,1)) %>% 
  mutate(lag = replace_na(lag, 0)) %>% 
  mutate(diff = x-lag) %>% 
  count(diff) %>%
  mutate(n = ifelse(diff == 3, n + 1, n)) %>% 
  summarise(prod = prod(n))


unbinary(str_c(rep(1,10),collapse = ""))

unbinary(good_breaks$option[1])
unbinary("0001111111")

ten_string(192)

ten_string <- function(num) {
  rev(as.numeric(intToBits(num))[1:10])
}



checker_initial <- function(num = 192, batch = 1) {
  
  sample <- ten_string(num = num)
  
  sample_length <- length(sample)
  
  beginning <- sample[1] + sample[2] + sample[3] 
  end <- sample[10] + sample[9] + sample[8] 
  
  check <-
    input_10 %>%
    slice(((batch*sample_length)-(sample_length - 1)):(batch*sample_length)) %>%
    mutate(sample = sample) %>%
    filter(sample == 1) %>% 
    mutate(lag = lag(x, 1)) %>%
    mutate(lag = replace_na(lag, x[1])) %>%
    mutate(diff = x - lag) %>%
    summarise(max_diff = max(diff))
  
  if (check$max_diff <= 3 & sum(sample) > 1 & beginning > 0 & end > 0) {
    option <- tibble(option = str_c(sample, collapse = ""), batch = batch)
    return(option)
  } else {
    option <- tibble(option = as.character("2222222222"), batch = batch)
    return(option)
  }
  
}

```


```{r}
library(tidyverse)
library(compositions)

input_10 <-
  tibble(x = read_lines(here::here("data_files", "advent10data.txt"))) %>% 
  # tibble(x = read_lines(here::here("data_files", "advent10data_test.txt"))) %>% 
  mutate(x = as.numeric(x)) %>% 
  arrange(x) 

test <-
input_10 %>% 
  mutate(id = row_number()) %>% 
  relocate(id) %>% 
  # bind_rows(tibble(id = c(0), x = c(0))) %>%
  # bind_rows(tibble(id = c(0,max(row_number(.)-1)), x = c(0,max(input_10$x)+1))) %>%
  bind_rows(tibble(id = c(0), x = c(0))) %>%
  arrange(id) %>% 
  mutate(lag = x-lag(x, 1)) %>% 
  mutate(lead = lead(x, 1)-x) %>% 
  rowwise() %>% 
  mutate(diff = max(lag,lead,na.rm = T)) %>% 
  ungroup() %>% as.data.frame() %>% 
  slice(-c(1,max(row_number()))) %>% 
  select(id,x,diff)
  # tail()
  # I()

as.data.frame(test)

tibble(
lengths = rle(test$diff)$lengths,
values = rle(test$diff)$values
) %>% 
  filter(values !=3) %>% 
  mutate(combinations = case_when(lengths == 4 ~ length_4,
                                  lengths == 3 ~ length_3,
                                  lengths == 2 ~ length_2,
                                  lengths == 1 ~ length_1)) %>% 
  pull(combinations) %>% prod()


length_4 <- choose(n = 4,k = 4) + choose(n = 4,k = 3) + choose(n = 4,k = 2) + choose(n = 4,k = 1) - 3
length_3 <- choose(n = 3,k = 3) + choose(n = 3,k = 2) + choose(n = 3,k = 1)
length_2 <- choose(n = 2,k = 2) + choose(n = 2,k = 1) + choose(n = 2,k = 0)
length_1 <- choose(n = 1,k = 1) + choose(n = 1,k = 0)

7*7*4*2*7*12
7*7*4*2*7*11
7*7*4*2*7*10
7*7*4*2*7*9
7*7*4*2*7*8
7*7*4*2*7*7



19208
```



## Ninth Day of Advent

```{r}
library(furrr)
plan(multiprocess)

input_9 <-
  tibble(x = read_lines(here::here("data_files", "advent9data.txt"))) %>%
  mutate(id = row_number()) %>%
  relocate(id, x) %>% 
  mutate(x = as.numeric(x))


search_function <- function(search_value){

value_of_interest <-
input_9 %>% 
  filter(id == search_value) %>% 
  pull(x)

search <-
input_9 %>%
  filter(id %in% c((search_value-25):(search_value-1))) %>%
  mutate(y = x) %>% 
  expand(x,y) %>% 
  distinct() %>% 
  mutate(z = x+y) %>% 
  filter(z == value_of_interest) %>% 
  count(z) %>% 
  mutate(search_value) %>% 
  relocate(search_value, z, n)

return(search)
}

solution <-
26:1000 %>% future_map_dfr(.f = ~search_function(search_value = .x), .progress = T)

# 506

solution %>% 
  mutate(missing = search_value - lag(search_value,1)) %>% 
  arrange(search_value) %>% 
  filter(search_value %in% 500:510)

input_9 %>% 
  filter(id == 503)

search_function(search_value = 289)

```

```{r}
num_of_interest <- 15353384

searcher <- function(num_rows_to_search){

input_9 %>% 
  mutate(group_sum = c(rep(0,num_rows_to_search-1),zoo::rollsum(x,num_rows_to_search))) %>%
  mutate(num_rows_to_search = num_rows_to_search) %>% 
  filter(group_sum == num_of_interest)
  
}

num_rows_to_search = 17

part_b_solution <-
2:499 %>% 
purrr::map_dfr(.f = ~searcher(num_rows_to_search = .x))


input_9 %>% 
  mutate(group_sum = c(rep(0,num_rows_to_search-1),zoo::rollsum(x,num_rows_to_search))) %>%
  mutate(num_rows_to_search = num_rows_to_search) %>% 
  filter(id %in% c((part_b_solution$id-(num_rows_to_search[1]-1)):part_b_solution$id)) %>% 
  mutate(test = sum(x)) %>% 
  summarise(range = range(x)) %>% 
  summarise(total = sum(range))

```


## Eigth Day of Advent

```{r}
input_8 <- tibble(x = read_lines(here::here("data_files", "advent8data.txt")))

current_state <-
input_8 %>% 
  extract(x, c("command", "information"), "(.*) (.*)", convert = TRUE) %>% 
  mutate(current_location = if_else(row_number()==1,1,0)) %>% 
  mutate(been_here = if_else(row_number()==1,1,0)) %>% 
  mutate(id = row_number()) %>% 
  mutate(accumulator = 0) %>% 
  relocate(id)

log_location <- function(data){
  out <-
  data %>% 
    rowwise() %>% 
    mutate(been_here = current_location + been_here) %>% 
    ungroup()
  return(out)
}

accumulator_val <- NULL

progress_program <- function(current_state){

temp <-
current_state %>% 
  dplyr::filter(current_location == 1)

if(temp$command == "acc"){
  current_state <-
  current_state %>% 
    mutate(accumulator = accumulator + temp$information) %>% 
    mutate(current_location =   c(rep(0,temp$id),1,rep(0,nrow(current_state)-temp$id-1))) %>% 
    log_location()
  } else if(temp$command == "jmp"){
  current_state <-
  current_state %>% 
    mutate(current_location = c(rep(0,temp$information+temp$id-1),1,rep(0,nrow(current_state)-(temp$information+temp$id)))) %>% 
    log_location()
  } else if(temp$command == "nop"){
    current_state <-
  current_state %>% 
    mutate(current_location = c(rep(0,temp$id),1,rep(0,nrow(current_state)-temp$id-1))) %>% 
    log_location()
  }

accumulator_val = append(accumulator_val, current_state$accumulator[1])
print(accumulator_val)

if(current_state %>% filter(been_here > 1) %>% nrow() > 0){
  print(current_state %>% filter(been_here > 1))
  done()
}

if(current_state %>% filter(current_location == 1) %>% pull(id) ==625 ){
    print(str_c(current_state$accumulator[1], " on row 625"))
  done()
}

return(current_state)

}

while (current_state %>% filter(been_here>1) %>% nrow() == 0) {
  current_state <- progress_program(current_state = current_state)
}

###

try_row_fun <-function(try_row = try_row){

try_row = 298

current_state <-
input_8 %>% 
  extract(x, c("command", "information"), "(.*) (.*)", convert = TRUE) %>% 
  mutate(current_location = if_else(row_number()==1,1,0)) %>% 
  mutate(been_here = if_else(row_number()==1,1,0)) %>% 
  mutate(id = row_number()) %>% 
  mutate(accumulator = 0) %>% 
  relocate(id)


if(current_state %>% filter(id == try_row) %>% select(command) %>% pull(command) == "acc") {
  print(str_c("acc with try_row at ", try_row))
} else {
  print(str_c("try row at ", try_row))
  begin_altered <-
    current_state %>%
    mutate(command = if_else(id == try_row, if_else(command == "jmp", "nop", "jmp"), command))
  
  while (begin_altered %>% filter(been_here > 1) %>% nrow() == 0) {
    begin_altered <- progress_program(current_state = begin_altered)
  }
  
  if (current_state %>% filter(current_location == 1) %>% pull(id) == 625) {
    stop("test")
  }
  
}

}

298:625 %>% purrr::map(~try_row_fun(try_row = .x))

try_row_fun(try_row = 5)

## its 1030 on iteration 298 -- found out because the program errored

```



## Seventh Day of Advent - FAIL

```{r}
source(here::here("data_files", "advent7data.R"))

df_of_bags <-
tibble(advent7data) %>% 
  separate_rows(advent7data, sep = "\n") %>% 
  mutate(id = row_number()) %>% 
  relocate(id)

bag_searcher <- function(inner_bag = "shiny gold", data_input = first_pass){
bags_of_interest <-
  data_input %>% 
  filter(str_detect(string = advent7data, pattern = inner_bag)) %>% 
  mutate(outter_bag = word(string = advent7data, start = 1,end = 2)) %>% 
  filter(outter_bag != inner_bag) %>% 
  summarise(outter_bag = str_c(outter_bag,collapse = "|")) %>% 
  pull(outter_bag)
  
  return(bags_of_interest)
}

# answer <-
  "shiny gold" %>%
  bag_searcher(data_input = df_of_bags) %>% 
  bag_searcher(data_input = df_of_bags) %>% 
  bag_searcher(data_input = df_of_bags) %>% 
  bag_searcher(data_input = df_of_bags) %>% 
  bag_searcher(data_input = df_of_bags) %>% 
  bag_searcher(data_input = df_of_bags) %>% 
  bag_searcher(data_input = df_of_bags) %>% 
  bag_searcher(data_input = df_of_bags) %>% 
  bag_searcher(data_input = df_of_bags) %>% 
  bag_searcher(data_input = df_of_bags) %>% 
  bag_searcher(data_input = df_of_bags) %>% 
  tibble() %>% 
  janitor::clean_names() %>% 
    rename(bags = x) %>% 
    separate_rows(bags, sep = "\\|") 
  
bag_breakdown <-
  df_of_bags %>% 
    mutate(outter_bag = word(string = advent7data, start = 1, end = 2)) %>% 
    tidyr::separate(col = advent7data, into = c(NA, "inner"),sep = "contain ") %>% 
    separate_rows(inner, sep = ",") %>% 
    mutate(inner = str_trim(string = inner)) %>% 
    mutate(num_bags = as.numeric(str_sub(string = inner, start = 1, end = 1))) %>% 
    mutate(num_bags = replace_na(data = num_bags,replace = 0)) %>% 
  mutate(inner = word(string = inner, start = 2,end = 3)) %>% 
  relocate(id, outter_bag, inner, num_bags)
  
starter <-
bag_breakdown %>%
  filter(outter_bag == "shiny gold") %>%
  # filter(num_bags != 0) %>%
  select(outter = outter_bag, inner, multiplier = num_bags) %>% 
  uncount(multiplier) %>% 
  mutate(total_so_far = nrow(.))
# 
data <- two_deep
open_bags <- function(data = starter){
next_level <-
data %>% 
  left_join(bag_breakdown, by = c("inner" = "outter_bag")) %>% 
  select(outter = inner, inner = inner.y, multiplier = num_bags, total_so_far) %>% 
  mutate(multiplier = if_else(multiplier==0,1,multiplier)) %>% 
  # as.data.frame() %>% 
  filter(!is.na(multiplier)) %>% 
  uncount(multiplier) %>% 
  mutate(total_so_far = nrow(.) + total_so_far[1])
return(next_level)
}


open_bags(data = starter) %>% 
  open_bags() %>%  
  # as.data.frame()
  open_bags() %>% 
  open_bags() %>% 
  open_bags() %>% 
  open_bags() %>%
  open_bags() %>%
  open_bags()

## Not Correct
```

## Seventh Day of Advent -- [David Robinson](https://twitter.com/drob/status/1336003816395845632/photo/1)

```{r}
input <- tibble(x = read_lines(here::here("data_files", "advent7data.txt")))

rules <-
input %>% 
  extract(x, c("color", "contents"), "(.*) bags contain (.*)\\.") %>% 
  separate_rows(contents, sep = ", ") %>% 
  extract(contents, c("number", "content_color"), "([\\d]*) (.*) bag", convert = TRUE, remove = FALSE) %>% 
  filter(!is.na(number))

contained_by <- function(cols, ...) {
  rules %>% 
    filter(content_color %in% cols) %>% 
    pull(color)
} 

accumulate(1:100, contained_by, .init = "shiny gold") %>% 
  tail(-1) %>% 
  unlist() %>% 
  n_distinct()

n_contain <- function(col) {
  r <- rules %>% 
    filter(color == col)
  
  sum(r$number * (1 + map_dbl(r$content_color, n_contain)))
  
}

n_contain(col = "shiny gold")

```



## Sixth Day of Advent

```{r}
library(tidytext)

source(here::here("data_files", "advent6data.R"))

tibble(advent6data) %>%
  separate_rows(advent6data, sep = c("\n\n")) %>%
  mutate(id = row_number()) %>%
  mutate(advent6data = str_remove_all(string = advent6data, pattern = "\n")) %>% 
  unnest_characters(word, advent6data) %>% 
  distinct(id,word)
  
tibble(advent6data) %>%
  separate_rows(advent6data, sep = c("\n\n")) %>%
  mutate(id = row_number()) %>% 
  mutate(people_in_group = str_count(string = advent6data, pattern = "\n")+1) %>% 
  mutate(advent6data = str_remove_all(string = advent6data, pattern = "\n")) %>% 
  unnest_characters(word, advent6data) %>% 
  count(id, word, people_in_group) %>% 
  filter(people_in_group == n)
  
```


## Fifth Day of Advent

```{r}
source(here::here("data_files", "advent5data.R"))
seats <- 
tibble(advent5data) %>% 
  mutate(first = if_else(str_sub(string = advent5data,start = 1,end = 1) == "F", 0, 64)) %>% 
  mutate(secon = if_else(str_sub(string = advent5data,start = 2,end = 2) == "F", 0, 32)) %>% 
  mutate(third = if_else(str_sub(string = advent5data,start = 3,end = 3) == "F", 0, 16)) %>% 
  mutate(forth = if_else(str_sub(string = advent5data,start = 4,end = 4) == "F", 0, 8)) %>% 
  mutate(fifth = if_else(str_sub(string = advent5data,start = 5,end = 5) == "F", 0, 4)) %>% 
  mutate(sixth = if_else(str_sub(string = advent5data,start = 6,end = 6) == "F", 0, 2)) %>% 
  mutate(seven = if_else(str_sub(string = advent5data,start = 7,end = 7) == "F", 0, 1)) %>% 
  mutate(side1 = if_else(str_sub(string = advent5data,start = 8,end = 8) == "L", 0, 4)) %>% 
  mutate(side2 = if_else(str_sub(string = advent5data,start = 9,end = 9) == "L", 0, 2)) %>% 
  mutate(side3 = if_else(str_sub(string = advent5data,start = 10,end = 10) == "L", 0, 1)) %>%
  rowwise() %>% 
  mutate(rows = sum(first,secon,third,forth,fifth,sixth,seven)) %>% 
  mutate(seat = sum(side1,side2,side3)) %>% 
  ungroup() %>% 
  mutate(seatid = rows * 8 + seat) 

seats %>% 
  filter(seatid == max(seatid))

seats %>% 
  arrange(rows, seat) %>% as.data.frame() %>% 
  mutate(distance = seatid - lag(seatid,1)) %>% 
  filter(distance != 1)

seats %>% 
  arrange(rows, seat) %>% as.data.frame() %>% 
  filter(seatid %in% 715:720)
  
```



## Fourth Day of Advent

```{r}
source(here::here("data_files", "advent4data.R"))
# advent4data

tibble(advent4data) %>%
  separate_rows(advent4data, sep = c("\n  \n|\n    \n")) %>% 
  mutate(ids = str_count(string = advent4data,pattern = c("byr|iyr|eyr|hgt|hcl|ecl|pid"))) %>% 
  count(ids) %>% 
  arrange(desc(ids))
  
tibble(advent4data) %>%
  separate_rows(advent4data, sep = c("\n  \n|\n    \n")) %>% 
  mutate(ids = str_count(string = advent4data,pattern = c("byr|iyr|eyr|hgt|hcl|ecl|pid"))) %>% 
  filter(ids == 7) %>% 
  mutate(advent4data = str_replace_all(string = advent4data, pattern = "\n", replacement = " ")) %>% 
  mutate(ids = row_number()) %>% 
  separate_rows(advent4data, sep = " ") %>% 
  filter(advent4data != "") %>% 
  separate(col = advent4data, into = c("name", "value"), sep = ":") %>% 
  # select(-ids) %>% 
  # group_by(ids) %>% 
  pivot_wider(names_from = name, values_from = value) %>% 
  select(-cid) %>% 
  mutate(across(.cols = c("byr","eyr","iyr"), .fns = ~as.numeric(.))) %>% 
  filter(byr >= 1920 & byr <= 2002 ) %>% 
  filter(iyr <= 2020 & iyr >= 2010) %>% 
  filter(eyr <= 2030 & eyr >= 2020) %>% 
  filter(str_detect(string = hgt,pattern = "cm") | str_detect(string = hgt,pattern = "in")) %>% 
  mutate(ht = as.numeric(str_remove_all(string = hgt, pattern = c("cm|in")))) %>%
  filter(c(str_detect(string = hgt, pattern = "cm") & ht >= 150 & ht <= 193) | c(str_detect(string = hgt, pattern = "in") & ht >= 59 & ht <= 76)) %>% 
  filter(str_sub(string = hcl,start = 1,end = 1)=="#") %>% 
  filter(str_length(string = hcl)==7) %>% 
  filter(ecl %in% c("amb", "blu", "brn", "gry", "grn", "hzl", "oth")) %>% 
  filter(str_length(pid)==9) %>% 
  nrow()
  
  
```


## Third Day of Advent

```{r}
source(here::here("data_files", "advent3data.R"))


repper <- function(vector = advent3data[1]){
  tibble(slope = vector %>% rep(967/3) %>% str_c(collapse = ""))
}

character_of_interest <- seq(from = 1, to = 967, by = 3)
length(character_of_interest)

advent3data[1] %>% repper()

slope <-
  advent3data %>% purrr::map_dfr(.f = ~ repper(.x))

slope %>% 
  mutate(character_of_interest = character_of_interest) %>% 
  mutate(n = nchar(slope)) %>% 
  mutate(obstacle = str_sub(string = slope, start = character_of_interest, end = character_of_interest)) %>% 
  count(obstacle)
```


```{r}
one_by_one <- seq(from = 1, by = 1, length.out = 323)
three_by_one <- seq(from = 1, by = 3, length.out = 323)
five_by_one <- seq(from = 1, by = 5, length.out = 323)
seven_by_one <- seq(from = 1, by = 7, length.out = 323)

one_by_two <- seq(from = 1, by = 1, length.out = 162)
length(three_by_one)


repper <- function(vector = advent3data[1]){
  tibble(slope = vector %>% rep(967/3) %>% str_c(collapse = ""))
}


advent3data[1] %>% repper()

slope <-
  advent3data %>% purrr::map_dfr(.f = ~ repper(.x))

slope_fun <- function(vec){
slope %>% 
  mutate(character_of_interest = vec) %>% 
  mutate(n = nchar(slope)) %>% 
  mutate(obstacle = str_sub(string = slope, start = character_of_interest, end = character_of_interest)) %>% 
  count(obstacle) %>% 
    mutate(id = vec[2]-vec[1])
}

first_group <-
list(one_by_one,three_by_one,five_by_one,seven_by_one) %>% 
  purrr::map_dfr(.f = ~slope_fun(.x))

slope_fun(vec = three_by_one) 

second_group <-
slope %>% 
  filter(row_number() %in% seq(from = 1, to = 323, by = 2)) %>% 
  mutate(character_of_interest = one_by_two) %>% 
  mutate(n = nchar(slope)) %>% 
  mutate(obstacle = str_sub(string = slope, start = character_of_interest, end = character_of_interest)) %>% 
  count(obstacle) %>% 
  mutate(id = character_of_interest[2]-character_of_interest[1]+10)


bind_rows(first_group,second_group) %>% 
  filter(obstacle == "#") %>% pull(n) %>% prod() %>% tibble()

```


## Second Day of Advent

```{r}
source(here::here("data_files", "advent2data.R"))
# advent2data

tibble(advent2data) %>% 
  mutate(id = row_number()) %>% 
  tidyr::separate(col = advent2data, into = c("first", "password"), sep = ": ") %>% 
  tidyr::separate(col = first, into = c("digits", "letter"), sep = " ")  %>% 
  tidyr::separate(col = digits, into = c("first", "second"), sep = "-") %>% 
  mutate(across(.cols = c("first","second"),.fns = ~as.integer(.))) %>% 
  mutate(count = str_count(string = password, pattern = letter)) %>% 
  relocate(id) %>% 
  filter(count <= second & count >= first) %>% 
  nrow()
  
  
tibble(advent2data) %>% 
  mutate(id = row_number()) %>% 
  tidyr::separate(col = advent2data, into = c("first", "password"), sep = ": ") %>% 
  tidyr::separate(col = first, into = c("digits", "letter"), sep = " ")  %>% 
  tidyr::separate(col = digits, into = c("first", "second"), sep = "-") %>% 
  mutate(across(.cols = c("first","second"),.fns = ~as.integer(.))) %>% 
  mutate(slot_a = str_sub(string = password, start = first,end = first)) %>% 
  mutate(slot_b = str_sub(string = password, start = second,end = second)) %>% 
  filter(slot_a != slot_b) %>% 
  filter(slot_a == letter | slot_b == letter) %>% 
  nrow()


```


## First Day of Advent

```{r}
source(here::here("data_files", "advent1data.R"))

advent_1  <- function(vector, lag) {
  tibble(vector = vector) %>%
    mutate(vector2 = lag(vector, lag)) %>% 
    filter(vector + vector2 == 2020) %>% 
    mutate(answer = vector * vector2)
} 

1:length(advent1data) %>%
  purrr::map_dfr(.f = ~advent_1(vector = advent1data, lag = .x)) %>% 
  pull(answer)

```

```{r}
library(tidyverse)
library(furrr)
plan(multiprocess)

advent_2  <- function(vector, lag_1, lag_2) {
  tibble(vector = vector) %>%
    mutate(vector2 = lag(vector, lag_1)) %>% 
    mutate(vector3 = lag(vector, lag_2)) %>% 
    filter(vector + vector2 + vector3 == 2020) %>% 
    mutate(answer = vector * vector2 * vector3)
} 

answer_2 <-
expand_grid(one = 1:length(advent1data), two = 1:length(advent1data)) %>% 
  filter(two > one) %>% 
  furrr::future_pmap_dfr(.f = ~advent_2(vector = advent1data, lag_1 = .x, lag_2 = .y), .progress = T) 
  
answer_2
```

